//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int job_id { get; set; }
        public int client_id { get; set; }
        public int worker_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public int job_status { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
