//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int skill_id { get; set; }
        public string skill_name { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
